### ISSUE TITLE
Add sigma point filters

### ISSUE THREAD

**Issue by CharlesCossette** [decargroup/pynav#26]
I suggest this be done in the following way. 

First, create a standalone function that generates unit sigma points `sigma_points = get_sigma_points(N, "unscented")`, where `"unscented"` can be replaced by either `"spherical"` or `"gausshermite"` or whatever other sigma-point scheme. This is used internally by the filter, but also a public function useful for other things

It is then possible to create a general `SigmaPointKalmanFilter(process_model, method = "unscented")`

However, just for ease-of-access, we can make quick convenience classes in the form:

```python 
class UnscentedKalmanFilter(SigmaPointKalmanFilter):
    def __init__(self, process_model):
        super().__init__(self, process_model,  method = "unscented")
```
For sigma-point generation in the prediction step, the noise statistics of the input, are needed. This can be provided as an optional argument in the prediction step:

```python
ukf.predict(x, u, dt, input_covariance = Q)
```
and then since noise is basically always additive to the input, `u.plus(sigma_point)` and feed to the process model. If `Q` is not provided, the input object can be checked for a `u.covariance` property. 

For sigma-point generation in the correction step, we currently always assume the noise is additive to the state. We will have to modify things elsewhere in pynav to add a more complicated option, but I have an idea. Nevertheless, we can currently pass state sigma points through the nonlinear process models

**Comment by PDeco** [comment]
Hey, I think adding Arturo to this would be a good idea. He has been looking into sigma point filters!
